# Generated by Django 4.2.10 on 2024-02-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='application',
            name='first_hackathon',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='application',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default='123-456-7890', max_length=12),
        ),
        migrations.AddField(
            model_name='application',
            name='q1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='q2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='team_member_1',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='team_member_2',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='team_member_3',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='year',
            field=models.CharField(choices=[('NTH', 'Ninth Grade'), ('TEN', 'Tenth Grade'), ('ELE', 'Eleventh Grade'), ('TWE', 'Twelfth Grade'), ('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Grad')], default='NTH', max_length=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('ACPT', 'Accepted'), ('RJCT', 'Rejected'), ('WLST', 'Waitlisted'), ('PROC', 'Processing')], default='PROC', max_length=4),
        ),
    ]
